### ISSUE TITLE
No support for processor groups

### ISSUE THREAD

**Issue by ionescu007** [tandasat/HyperPlatform#12]
Hi,

Hyperplatform is currently using Vista/deprecated CPU management/query APIs such as KeGetCurrentProcessorNumber, KeSetSystemAffinityEx, etc. These APIs do not function correctly when "processor groups" are enabled.

You should test hyperplatform with the information available here: https://msdn.microsoft.com/en-us/library/windows/hardware/ff542298(v=vs.85).aspx. This lets you test processor groups with as little as 2 processors (4 is better).

A few examples, you should use KeGetCurrentProcessorNumberEx(NULL) instead of the non-Ex version.  You should use KeSetSystemGroupAffinityThread as you hop around processors, and pass in the correct group affinity for each group being iterated.

I realize you might say "nobody cares about this, no-one will run this on NUMA systems with > 64 processors"...

**Comment by tandasat** [comment]
Thanks for reporting the issue with clear information. 

While no one is going to run the hypervisor with more than 64 processors (I would say so), HyperPlatform should still support processor groups or states that it is unsupported by design. I will consider updating code, as it makes code more portable.

Processor groups was not supported mostly because I was unaware of the bcdedit option and unable to test code even if it was written. Thank you for letting me know the page; that is great resource.

Thank you,
