### ISSUE TITLE
About Shadow Hook Question

### ISSUE THREAD

**Issue by MaMyYyY** [tandasat/HyperPlatform#35]
An export name to hook is ok,(SSDT) 
How hook noexport api? like eg: NtGdiBitBlt (shadow hook)

CONSTANT_STRING(L"NTGDIBITBLT"),
        DdimonpHandleNtGdiBitblt, nullptr,    not work  
                                                                    

thank you..

**Comment by tandasat** [comment]
You can implement code to resolve unexported function's address instead of using DdimonpEnumExportedSymbols().  

There are some common strategies for it:
- finding function pointers -- if a function address is stored in a table (like SSDT, SSDT shadow, IDT), you may use it
- searching byte pattern -- you may collect byte patterns and use UtilMemMem() 
- using symbol info -- get an address using debug symbols if symbol info is available. My hyperplatform_log_parser project will be useful as a reference

**Comment by MaMyYyY** [comment]
ok, thanks
