### ISSUE TITLE
Is there any way to install shadow hook for function in win32k.sys?

### ISSUE THREAD

**Issue by hzqst** [tandasat/HyperPlatform#37]
I tried `KeStackAttachProcess` to csrss.exe before installing shadow hook to win32k!NtUserSetWindowsHookEx, and `KeUnstackAttachProcess` to switch the context back to System  process after installing hook.
but my detour function never get called.

Windbg said that win32k!NtUserSetWindowsHookEx is in session address space that I can't set software- breakpoint at it or it may cause bugcheck. I guess this is the reason why my shadow hook won't work since the shadow hook need int3 breakpoint to work.

**Comment by tandasat** [comment]
There are potentially many chances of failure because DdiMon assumes that a target address is in non-session, kernel address space. 

One potential reason is that `ShpEnablePageShadowingForExec()` might be failing to get a right `ept_pt_entry` because `UtilPaFromVa()` attempts to get PA of win32k!NtUserSetWindowsHookEx with system's CR3. You can check if UtilPaFromVa() is called with right CR3 value (in this case, that of csrss.exe) and returned expected PA.

Other thing I would try is setting breakpoint on `ShHandleBreakpoint()` to see if the breakpoint is set and active, and if so, why the hook function is not called. 

I presume that setting 0xCC works even for session address space, as quick test with Windbg showed that breakpoint worked for win32k!NtUserSetWindowsHookEx despite the warning message. 
```
0: kd> bp  win32kfull!NtUserSetWindowsHookEx
WARNING: Software breakpoints on session addresses can cause bugchecks.
Use hardware execution breakpoints (ba e) if possible.

0: kd> bp win32k!NtUserSetWindowsHookEx
WARNING: Software breakpoints on session addresses can cause bugchecks.
Use hardware execution breakpoints (ba e) if possible.

0: kd> g
Breakpoint 1 hit
win32k!NtUserSetWindowsHookEx:
ffffe288`a0731d3a jmp     qword ptr [win32k!_imp_NtUserSetWindowsHookEx (ffffe288`a07538a8)]

1: kd> kn
 # Child-SP          RetAddr           Call Site
00 ffffd000`8a4bfa88 fffff802`85b5ff93 win32k!NtUserSetWindowsHookEx
01 ffffd000`8a4bfa90 00007ffd`58b32204 nt!KiSystemServiceCopyEnd+0x13
02 000000e3`9d2ff388 00007ffd`5aaf75a8 win32u!NtUserSetWindowsHookEx+0x14
```

**Comment by hzqst** [comment]
Thanks, it works fine when I switch the context to csrss's before every call to `UtilPaFromVa`.
