### ISSUE TITLE
Clarify supported virtualization platforms

### ISSUE THREAD

**Issue by hatRiot** [tandasat/HyperPlatform#71]
This might be a moving target issue, but it appears that at this time, only VMWare products are supported. Can you confirm?

I've tried VirtualBox, but as of 6.1 VB does [not support SLAT passthru](https://forums.virtualbox.org/viewtopic.php?f=6&t=95302) and this appears to be a requirement for running hypervisors inside the VM.

Hyper-V also seems like it should work as it has the required passthru support, but I've had some issues. On initial run, it appears to kill the VM (not BSOD/crash, just completely lock up) right after the `__vmx_vmlaunch` call. I'm not familiar enough (yet) with the code to know exactly why.

VMWare Workstation and Player both work out of the box.

These were all tested on a Windows 10 v1909 running Win10 v1909 virtual machines.

**Comment by tandasat** [comment]
That's correct that only VMware products are supported. I can, however, clarify tips and requirements for other platforms in case you are curious. 

* VirtualBox - Not usable out of the box, because of the reason you mentioned. If you disable EPT, it might work.
* Hyper-V - A VM locks up because the underneath Hyper-V "forwards" VM-exits that we did not enable assuming that we behave like Hyper-V (which we do not). You may test on Hyper-V by applying an updates outlined in this [blog post](https://rayanfam.com/topics/hypervisor-from-scratch-part-8/), but I found this can be very unstable depending on system configurations (ie, multi-core VM IIRC)
* Parallels - It *should* work but I have never tested.
* KVM (Qemu on Linux host) - I heard it worked if you disable Hyper-V enlightment.

**Comment by hatRiot** [comment]
Great information, thanks @tandasat!
