### ISSUE TITLE
Bugcheck while attempting to inject #UD

### ISSUE THREAD

**Issue by tdavis165** [tandasat/HyperPlatform#74]
### Description

Hello, I am attempting to inject a #UD Exception in VmmpHandleVmx In order to disable assembly instructions like vmread.

How ever if the exception is injected from CPL 0 It causes a bug check. So I am only able to run this code if the CPL is above 0 ore the exception bug checks the system.

### Expected behavior

An invalid opcode exception is returned to the guest, giving the illusion that the instruction is invalid

### Actual behavior

If the vmexit is called from CPL 0, The system crashes due to the exception not being handled

### Steps to reproduce the problem

```
static void VmmpHandleVmx( GuestContext* guest_context ) {
  // The following if statement will only run if the code is executed above kernel level 0
  // If this if statement is removed, the system crashes when executed.
  if ( VmmpGetGuestCpl( ) > 0 )
    VmmpInjectInterruption( InterruptionType::kHardwareException, InterruptionVector::kInvalidOpcodeException, false, 0 );

  guest_context->flag_reg.fields.cf = true;  // Error without status
  guest_context->flag_reg.fields.pf = false;
  guest_context->flag_reg.fields.af = false;
  guest_context->flag_reg.fields.zf = false;  // Error without status
  guest_context->flag_reg.fields.sf = false;
  guest_context->flag_reg.fields.of = false;
  UtilVmWrite( VmcsField::kGuestRflags, guest_context->flag_reg.all );

  VmmpAdjustGuestInstructionPointer( guest_context );
}
```

### Specifications
- Commit (eg, 2099af7): Latest

- OS version (ie, output of the "ver" command, or N/A): 1809

- Architecture: x64

- Hardware (eg, Physical, VMware 15, Bochs, or N/A): Physical

**Comment by tandasat** [comment]
This is expected behavior. How the guest handles #GP is up to the guest and nothing to do with how the host injects it. 

If you want to make the guest believe that VMX instructions are not available, then you should manipulate the results of CPUID etc and indicates that, on the top of injecting #GP. Then well-behaved guest will not attempt to use VMX-instructions. If the guest still does, it is a bug of the guest (ie, a driver) and system crash SHOULD happen.
