### ISSUE TITLE
Question about VmmpGetGuestCpl()

### ISSUE THREAD

**Issue by jonomango** [tandasat/HyperPlatform#79]
Hello,

I had a quick question about the implementation of `VmmpGetGuestCpl()` in vmm.cpp. I was under the impression that the CPL of a processor is stored in the lower 2 bits of the CS selector (the RPL?), yet you're accessing it through the access rights of the SS segment descriptor (the DPL?). It probably achieves the same effect, but I was just curious as to why it was done this way or if my understanding of CPL was incorrect. I was expecting to see something more along the lines of 
```cpp
static UCHAR VmmpGetGuestCpl() {
  SegmentSelector cs{ UtilVmRead(VmcsField::kGuestCsSelector) };
  return cs.rpl;
}
``` 
Any clarification is really appreciated since the concept of CPL/RPL/DPL still confuses me a bit. Thanks!

**Comment by tandasat** [comment]
Your understanding is correct that CS does indicate CPL. 

SS does too, and in some edge case *on AMD processor*, CS may not corresponds to CPL (IIRC, details are in one of KVM patches). This is effectively irrelevant to this project since it is not designed for AMD, so you are good to pick whichever you think most make sense (understandable).
